
services:
  # ===================== DATABASE =====================
  postgres:
    image: postgres:15
    container_name: hostel_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  # ===================== BACKEND =====================
  backend:
    build: ./backend
    container_name: hostel_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      SET_WEBHOOK: "true"
    depends_on:
      - postgres
    expose:
      - "8000"
    command: >
      gunicorn main:app
      -k uvicorn.workers.UvicornWorker
      -w 4
      -b 0.0.0.0:8000

  webhook-init:
    image: hostel-backend
    container_name: hostel_webhook_init
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    command: python set_webhook.py
    restart: "no"
  # ===================== TELEGRAM MINI APP =====================
  miniapp:
    build: ./miniapp
    container_name: hostel_miniapp
    restart: always
    env_file:
      - ./miniapp/.env
    depends_on:
      - backend
    expose:
      - "8002"

  # ===================== NGINX (HTTPS) =====================
  nginx:
    image: nginx:alpine
    container_name: hostel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./miniapp/static:/var/www/miniapp/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - miniapp


# ===================== PERSISTENT VOLUMES =====================
volumes:
  postgres_data:
