upstream backend {
    server backend:8000;
    keepalive 32;
}

upstream miniapp {
    server miniapp:8002;
    keepalive 16;
}

server {
    listen 80;
    server_name hmsuz.com www.hmsuz.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;   # ❌ remove http2
    server_name hmsuz.com www.hmsuz.com;

    ssl_certificate     /etc/letsencrypt/live/hmsuz.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hmsuz.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    resolver 8.8.8.8 ipv6=off;   # 🔥 VERY IMPORTANT

    location /api/ {
        proxy_pass http://backend;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_buffering off;
        proxy_connect_timeout 3s;
        proxy_read_timeout 30s;
    }

    location /ws {
        proxy_pass http://backend/ws;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_read_timeout 86400;
    }


    location /tg/webhook {
        proxy_pass http://backend/tg/webhook;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }


    location / {
        proxy_pass http://miniapp;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
    }
}
